import prisma from "../lib/db.js";
import type { PlanType } from "../generated/prisma/client.js";

/**
 * Queries user subscription plan details, plan expiration date, and lifetime artifact generation count.
 *
 * @param userId - Unique identifier of the user
 * @returns Promise resolving to plan details object or null
 */
export function findUserPlanDetails(userId: string) {
    return prisma.user.findUnique({
        where: { id: userId },
        select: {
            id: true,
            name: true,
            email: true,
            plan: true,
            planExpiresAt: true,
            totalArtifactsCreated: true,
        },
    });
}

/**
 * Queries a user record and their profile information by user ID.
 *
 * @param userId - Unique identifier of the user
 * @returns Promise resolving to user profile record or null
 */
export function findUserById(userId: string) {
    return prisma.user.findUnique({
        where: { id: userId },
        select: {
            id: true,
            name: true,
            email: true,
            image: true,
            plan: true,
            planExpiresAt: true,
            totalArtifactsCreated: true,
            createdAt: true,
            updatedAt: true,
        },
    });
}

/**
 * Updates a user's subscription tier (e.g. FREE -> PRO -> PRO_PLUS).
 *
 * @param userId - Unique identifier of the user
 * @param plan - Target PlanType enum value
 * @returns Promise resolving to updated user summary
 */
export function updateUserPlan(userId: string, plan: PlanType) {
    return prisma.user.update({
        where: { id: userId },
        data: { plan },
        select: {
            id: true,
            email: true,
            name: true,
            plan: true,
        },
    });
}

/**
 * Atomically increments a user's lifetime total artifact creation counter by 1.
 *
 * @param userId - Unique identifier of the user
 * @returns Promise resolving to updated artifact counter
 */
export function incrementUserArtifactCount(userId: string) {
    return prisma.user.update({
        where: { id: userId },
        data: { totalArtifactsCreated: { increment: 1 } },
        select: { totalArtifactsCreated: true },
    });
}

/**
 * Retrieves the total count of learning artifacts generated by a user.
 *
 * @param userId - Unique identifier of the user
 * @returns Promise resolving to totalArtifactsCreated object or null
 */
export function findUserTotalArtifacts(userId: string) {
    return prisma.user.findUnique({
        where: { id: userId },
        select: { totalArtifactsCreated: true },
    });
}

/**
 * Counts the total number of workspaces owned by a user.
 *
 * @param userId - Unique identifier of the user
 * @returns Promise resolving to total workspace count integer
 */
export function countUserWorkspaces(userId: string) {
    return prisma.workspace.count({
        where: { userId },
    });
}

/**
 * Counts the total number of sources across all workspaces owned by a user.
 *
 * @param userId - Unique identifier of the user
 * @returns Promise resolving to total source count integer
 */
export function countUserSources(userId: string) {
    return prisma.source.count({
        where: { workspace: { userId } },
    });
}

/**
 * Counts the total number of user chat messages sent across all workspaces owned by a user.
 *
 * @param userId - Unique identifier of the user
 * @returns Promise resolving to user message count integer
 */
export function countUserMessages(userId: string) {
    return prisma.message.count({
        where: {
            role: "USER",
            conversation: { workspace: { userId } },
        },
    });
}
